import type { Metadata } from "next";
import { Navbar } from "@/components/layouts/NavBar";

export const metadata: Metadata = {
    title: "Tour Flow",
    description: "Generated by create next app",
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar />
            {children}
        </>
    );
}
